Update to the latest rules_scala
```
❯ bazel build //src/main/scala/example:example
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
WARNING: Download from https://mirror.bazel.build/raw.githubusercontent.com/bazelbuild/bazel/0.29.1/src/main/java/com/google/devtools/build/lib/bazel/rules/java/java_stub_template.txt failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
ERROR: /Users/lgeirsson/dev/playground-bazel/src/main/scala/example/BUILD:3:1: in scala_library rule //src/main/scala/example:example:
Traceback (most recent call last):
	File "/Users/lgeirsson/dev/playground-bazel/src/main/scala/example/BUILD", line 3
		scala_library(name = 'example')
	File "/private/var/tmp/_bazel_lgeirsson/7c19fd0800e09fdb570709e692a06160/external/rules_scala_annex/rules/scala.bzl", line 209, in _scala_library_implementation
		_run_phases(ctx, <1 more arguments>)
	File "/private/var/tmp/_bazel_lgeirsson/7c19fd0800e09fdb570709e692a06160/external/rules_scala_annex/rules/private/phases/api.bzl", line 28, in _run_phases
		function(ctx, g)
	File "/private/var/tmp/_bazel_lgeirsson/7c19fd0800e09fdb570709e692a06160/external/rules_scala_annex/rules/private/phases/phase_zinc_compile.bzl", line 99, in function
		_ZincInfo(apis = apis, <4 more arguments>)
	File "/private/var/tmp/_bazel_lgeirsson/7c19fd0800e09fdb570709e692a06160/external/rules_scala_annex/rules/private/phases/phase_zinc_compile.bzl", line 104, in _ZincInfo
		depset(<2 more arguments>)
depset elements must not be mutable values
ERROR: Analysis of target '//src/main/scala/example:example' failed; build aborted: Analysis of target '//src/main/scala/example:example' failed
INFO: Elapsed time: 63.756s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (116 packages loaded, 1485 targets configured)
```